### ISSUE TITLE
(Linux) linux-template release not working

### ISSUE THREAD

**Issue by alsed** [Redot-Engine/redot-engine#675] opened 2024-10-11 18:17 UTC
### Tested versions

4.4 beta

### System information

Fedora 40 Workstation

### Issue description

After marking the binary as executable, and try to run the binary 
the screen informs an error: `Could not load data at path "."`
after confirming the message, returns to desktop.

![Captura desde 2024-10-11 15-09-37](https://github.com/user-attachments/assets/5dc6fec2-e0bb-43a4-bfc2-c09c57fdbb02)

### Steps to reproduce

download [redot-linux-template](https://github.com/Redot-Engine/redot-engine/releases/download/2024101114/redot-linux-template.zip), extract zip, mark the binary as executable, run it.

### Minimal reproduction project (MRP)

N/A

**Comment by SkogiB** [comment] 2024-10-11 18:24
Oh, you don't run this one. I know it's kinda messy, but the templates are for your export manager, not for running the editor. We can fix this weird stuff once we have a site up, but you run the other executable from the release and when you go to export your project you must point the Custom Release Export Template at the template executable.

Double check that's the arrangement and let me know what's going on

**Comment by Spartan322** [comment] 2024-10-11 21:23
The editor builds should be more obviously the ones to download, we also need to fix downloading templates for our stuff.

**Comment by alsed** [comment] 2024-10-11 21:30
This issue seems to be the same that #673

**Comment by Spartan322** [comment] 2024-10-11 21:55
I'm closing this as a duplicate of #673 then

**Closed by Spartan322** 2024-10-11 21:55 UTC
Labels: bug
