### ISSUE TITLE
Creating a folder displays "res://" as the parent

### ISSUE THREAD

**Issue by StudioSyndiCatCaius** [Redot-Engine/redot-engine#666] opened 2024-10-11 16:11 UTC
### Tested versions

4.4 Beta

### System information

Win 11  -  4.4 Beta  - Forward+  

### Issue description

When I add a new folder to my project, it displays it as a child folder of "res://", even though the folder heirarchy in WIn explorer is correct. Seems to correct itself when minimizing and re-maximizing the editor. So on some refresh event?
![5b70a36a3820d9a90d48669c2f6ed770](https://github.com/user-attachments/assets/ee68c60e-5ebc-43a5-99d7-814a6a9cc419)

### Steps to reproduce

Just try adding a new folder or subfolder.

### Minimal reproduction project (MRP)

The project might not help, since it isn't actually creating the "res://" folder, only saying it has.
[test3d_error.zip](https://github.com/user-attachments/files/17345096/test3d_error.zip)

**Comment by AlchemicRaker** [comment] 2024-10-11 17:43
I was able to recreate this issue on WIndows. The hierarchy in the FIleSystem treeview is borked, but clicking away and then reforcusing the redot engine window is enough to prompt the treeview to refresh and correct itself.

**Steps to Recreate on Windows:**

1. in a new project, create a folder "Foo" under "res://". This folder appears correctly.
2. within the folder "Foo", create a new folder "Bar". Bar will appear with the path: "res://", "Foo", "res://", "Bar".
3. alt-tab to some other program, and then alt-tab back to redot. The treeview will correct itself, fixing the path to "res://", "Foo", "Bar"

This error does not occur when creating new folders directly within the top-level "res://", only within its descendants.

![image](https://github.com/user-attachments/assets/379de7e5-096c-4447-9c96-913c225bc599)

**Comment by SkogiB** [comment] 2024-10-11 18:47
This one may be fixed by merging in upstream commits on Godot master, we'll see how we're looking once we're caught back up, hang tight

**Comment by valkyrienyanko** [comment] 2024-10-14 06:04
I was also able to reproduce this issue on Windows 11 Redot v4.4.dev.mono.gh [1c7d7fa8d]

**Comment by SkogiB** [comment] 2024-10-14 11:58
> I was also able to reproduce this issue on Windows 11 Redot v4.4.dev.mono.gh [[1c7d7fa](https://github.com/Redot-Engine/redot-engine/commit/1c7d7fa8d2ca3a7c4b7645cf534da16d26cf621c)]

We've determined that this was indeed a bug caused by Godot's dev build, not by us, so we're going to close it as we expect them to fix it upstream

**Closed by SkogiB** 2024-10-14 11:58 UTC
Labels: bug
