### ISSUE TITLE
Light bleeding

### ISSUE THREAD

**Issue by daxime** [Redot-Engine/redot-engine#683] opened 2024-10-11 23:25 UTC
### Tested versions

Godot Engine v4.2 and 4.3
Redot Engine v4.4.dev.custom_build.4f67c65d2

### System information

Manjaro - Redot Engine v4.4.dev.custom_build.4f67c65d2

### Issue description

When a light source is close to a wall, the light will pass through the wall. 

### Steps to reproduce

Here, we see the source of the light
![Capture d’écran du 2024-10-11 22-32-16](https://github.com/user-attachments/assets/f083c280-179d-475a-8808-7619a3f0869d)

And here on the other side of the wall, on the floor there's a littlebit of light, and on the lower edge of the tunnel there's an even stronger reflection of the light source.
![Capture d’écran du 2024-10-11 22-32-02](https://github.com/user-attachments/assets/78597e0e-e364-4d4f-85e5-6238e5447e0c)

### Minimal reproduction project (MRP)

[bug-report-01.zip](https://github.com/user-attachments/files/17348082/bug-report-01.zip)

**Comment by Spartan322** [comment] 2024-10-12 02:41
Pretty certain this is a Godot issue, it would be helpful to have a reference in the Godot issue tracker for this.

**Comment by daxime** [comment] 2024-10-12 13:07
I have found this :
https://github.com/godotengine/godot/issues/87815

**Comment by SkogiB** [comment] 2024-10-13 13:57
> I have found this : [godotengine#87815](https://github.com/godotengine/godot/issues/87815)

Thank you, are you also using the baked lightmap features and all that in your project? I have a strong feeling we can close this as a known issue not caused by Redot

**Comment by daxime** [comment] 2024-10-13 18:02
Good evening,
I kept looking and I realized that in the MPR I forgot to export one side of the wall. By exporting it correctly, there was no more problem. So I searched in my project to see the differences and finally my problem came from the “shadow mode” which was on “paraboloid”. I reset it to the default values and I no longer have any problems with the light.

Sorry for the inconvenience ...

**Closed** 2024-10-13 18:03 UTC
Labels: bug
